<?php

/**
 * @var $this  \Gentoma\Helpdesk\Block\Index\Index
 * @var $block \Gentoma\Helpdesk\Block\Index\Index
 */
?>


<?php
$form_class = $block->bem->getBlock();
$field_class = $block->bem->element('field');
$label_class = $block->bem->element('field__label');
$input_class = $block->bem->element('field__input');
$submit_class = $block->bem->element('field__submit');
?>

<form class="<?= $form_class; ?>" method="POST"
      action="<?= $block->getFromAction() ?>">


    <div class="<?= $field_class ?>">
        <label class="<?= $label_class ?>"><?= __('Title') ?></label>

        <input class="<?= $input_class ?>" type="text"
               maxlength="255"
               name="title"
               data-validate="{required:true}">
    </div>

    <div class="<?= $field_class ?>">
        <label class="<?= $label_class ?>"><?= __('Level') ?></label>

        <select class="<?= $input_class ?>" name="level">
            <?php foreach ($this->getLeveles() as $key => $val): ?>
                <option value="<?= $key; ?>"><?= $val ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="<?= $field_class ?>">
        <?= $block->getBlockHtml('formkey') ?>

        <input class="<?= $submit_class ?>" type="submit"
               value="<?= __('Send ticket') ?>"
               name="submit"
               required>
    </div>

</form>

<?php
$tickets = $block->getTickets();
?>

<?php if ($tickets->count()): ?>
    <table class="data-grid">
        <thead>
        <tr>
            <th><?= __('ID') ?></th>
            <th><?= __('Title') ?></th>
            <th><?= __('Created At') ?></th>
            <th><?= __('Severity') ?></th>
            <th><?= __('Status') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($tickets as $t): ?>
            <tr>
                <td><?= $t->getId() ?></td>
                <td><?= $block->escapeHtml($t->getTitle()) ?></td>
                <td><?= $t->getCreatedAt() ?></td>
                <td><?= $t->getLevelAsText() ?></td>
                <td><?= $t->getStatusAsText() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
